title: Victor Almeida
#email: your-email@example.com
description: > # this means to ignore newlines until "baseurl:"
  My personal site, an output of something to the world.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://victortxa.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  victortxa
linkedin_username: victorxalmeida

# Build settings
markdown: kramdown
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
# Other options
permalink: blog/:year/:month/:title


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Following this tutorial http://svmiller.com/blog/2015/08/create-your-website-in-jekyll/
#jekyll serve --force_polling
